spring:
  ai:
    openai:
      api-key: "YOUR_API_KEY"
      chat:
        base-url: https://generativelanguage.googleapis.com
        completions-path: /v1beta/openai/chat/completions
        options:
          model: <YOUR_MODEL>
